In [1]:
import numpy as np
'''
Introduction Part
* np.array([[],[]]) --> Creation of array
* np.zeros((rows,columns)) --> creation of array with all elements 0
* np.ones((rows,columns)) --> creation of array with all elements 0
* np.full((rows,columns),number to be filled) --> creation of array with all elements of the same number provided
* np.arange(start,stop,step) --> creation of array with the elements from the start to the stop with the steps needed to be included
* np.eye(size) --> creation of an identity matrix

'''

'\nIntroduction Part\n* np.array([[],[]]) --> Creation of array\n* np.zeros((rows,columns)) --> creation of array with all elements 0\n* np.ones((rows,columns)) --> creation of array with all elements 0\n* np.full((rows,columns),number to be filled) --> creation of array with all elements of the same number provided\n* np.arange(start,stop,step) --> creation of array with the elements from the start to the stop with the steps needed to be included\n* np.eye(size) --> creation of an identity matrix\n\n'

In [2]:
arr1 = np.array([[1,3,5],[2,4,6],[5,8,9]])
print("arr1 =",arr1)

arr2 = np.zeros((2,3))
print("arr2 =",arr2)

arr3 = np.ones((2,3))
print("arr3 =",arr3)

arr4 = np.full((2,3),5)
print("arr4 =",arr4)

arr5 = np.arange(1,10,2)
print("arr5 =",arr5)

arr6 = np.eye(4)
print("arr6 =",arr6)

arr1 = [[1 3 5]
 [2 4 6]
 [5 8 9]]
arr2 = [[0. 0. 0.]
 [0. 0. 0.]]
arr3 = [[1. 1. 1.]
 [1. 1. 1.]]
arr4 = [[5 5 5]
 [5 5 5]]
arr5 = [1 3 5 7 9]
arr6 = [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
'''
Basics
* arr.shape --> shows the shape of the array
* arr.size --> shows the size of the array
* arr.ndim --> shows the dimension of the array
* arr.dtype --> shows the data type of the array
* arr.astype(data type) --> converts the array into the required data type
* we can also add, sum, div, mul, power (**) in all elements of a single array by arr (+,-,*,/,**) number required
'''

'\nBasics\n* arr.shape --> shows the shape of the array\n* arr.size --> shows the size of the array\n* arr.ndim --> shows the dimension of the array\n* arr.dtype --> shows the data type of the array\n* arr.astype(data type) --> converts the array into the required data type\n* we can also add, sum, div, mul, power (**) in all elements of a single array by arr (+,-,*,/,**) number required\n'

In [4]:
arr7 = np.array([[1,2,3],[4,5,6]])
array_conv = arr7.astype(float)
print("shape =",arr7.shape)
print("size =",arr7.size)
print("ndim =",arr7.ndim)
print("dtype =",arr7.dtype)
arr8 = np.array([[1,2,3,4,5,6,7,8,9]])
print("array_conv =",array_conv)
arr_sum = arr7 + 5
print("arr_sum =",arr_sum)

shape = (2, 3)
size = 6
ndim = 2
dtype = int64
array_conv = [[1. 2. 3.]
 [4. 5. 6.]]
arr_sum = [[ 6  7  8]
 [ 9 10 11]]


In [5]:
'''
Aggregation Function
* np.sum(arr)
* np.mean(arr)
* np.min(arr)  --> minimum value
* np.max(arr)  --> maximum value
* np.std(arr)  --> standard deviation
* np.var(arr)  --> variance

'''

'\nAggregation Function\n* np.sum(arr)\n* np.mean(arr)\n* np.min(arr)  --> minimum value\n* np.max(arr)  --> maximum value\n* np.std(arr)  --> standard deviation\n* np.var(arr)  --> variance\n\n'

In [6]:
print( "sum =", np.sum(arr8))
print("mean =", np.mean(arr8))
print("min =", np.min(arr8))
print("max =", np.max(arr8))
print("std =", np.std(arr8))
print("var =", np.var(arr8))

sum = 45
mean = 5.0
min = 1
max = 9
std = 2.581988897471611
var = 6.666666666666667


In [7]:
'''
Indexing
* arr[index] --> select the required indexed value if negative then index is counted from the last ( -1 is the last value)
* arr[start:stop:step] --> choose the value from the start to the stop with the steps required, negative value means reversed order
* arr[start:stop]
* arr[::step] --> choose all values with the steps required
* arr[[index1,index2,index3]] --> choose multiple indexed values
* arr[::-1] --> reverse the array
* arr[condition] --> choose the values based on the condition provided

'''

'\nIndexing\n* arr[index] --> select the required indexed value if negative then index is counted from the last ( -1 is the last value)\n* arr[start:stop:step] --> choose the value from the start to the stop with the steps required, negative value means reversed order\n* arr[start:stop]\n* arr[::step] --> choose all values with the steps required\n* arr[[index1,index2,index3]] --> choose multiple indexed values\n* arr[::-1] --> reverse the array\n* arr[condition] --> choose the values based on the condition provided\n\n'

In [8]:
array9 = np.array([1,2,3,4,5,6,7,8,9])
print(array9[2])
print(array9[2:6:2])
print(array9[2:6])
print(array9[::2])
print(array9[[1,3,5]])
print(array9[::-1])
print(array9[array9>5])

3
[3 5]
[3 4 5 6]
[1 3 5 7 9]
[2 4 6]
[9 8 7 6 5 4 3 2 1]
[6 7 8 9]


In [9]:
'''
Reshaping
* arr.reshape(rows,columns) --> reshape the array into the required shape only if the dimensions are satisfied
(reshaing doesn't create copy of the array it just creates a new view of the array)

Flattening
* arr.flatten() --> converts multi-dimensional array into 1-D array (flattening creates a copy of the array)
* arr.ravel() --> converts multi-dimensional array into 1-D array (ravel creates a view of the array)

'''

"\nReshaping\n* arr.reshape(rows,columns) --> reshape the array into the required shape only if the dimensions are satisfied\n(reshaing doesn't create copy of the array it just creates a new view of the array)\n\nFlattening\n* arr.flatten() --> converts multi-dimensional array into 1-D array (flattening creates a copy of the array)\n* arr.ravel() --> converts multi-dimensional array into 1-D array (ravel creates a view of the array)\n\n"

In [10]:
arr_reshaped = array9.reshape(3,3)
print("arr_reshaped =\n",arr_reshaped)
arr_flattened = arr_reshaped.flatten()
print("arr_flattened =",arr_flattened)
arr_raveled = arr_reshaped.ravel()
print("arr_raveled =",arr_raveled)

arr_reshaped =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr_flattened = [1 2 3 4 5 6 7 8 9]
arr_raveled = [1 2 3 4 5 6 7 8 9]


In [11]:
'''
Advanced Numpy

Inserting
* np.insert(arr, index, value, axis) --> inserts the value at the required index along the specified axis (0 for rows and 1 for columns)

'''

'\nAdvanced Numpy\n\nInserting\n* np.insert(arr, index, value, axis) --> inserts the value at the required index along the specified axis (0 for rows and 1 for columns)\n\n'

In [12]:
new_1darray = np.array([1,2,3,4,5,6,7,8,9])
new_2darray = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("1d aray = \n",np.insert(new_1darray, 5, 10, axis = 0))
print("2d array, axis 0 = \n",np.insert(new_2darray, 1, 10, axis = 0))
print("2d array, axis 1 = \n ",np.insert(new_2darray, 1, 10, axis = 1))

1d aray = 
 [ 1  2  3  4  5 10  6  7  8  9]
2d array, axis 0 = 
 [[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
2d array, axis 1 = 
  [[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


In [13]:
'''
Append and Concatenate
* np.append(arr1, arr2, axis) --> appends arr2 to arr1 along the specified axis (0 for rows and 1 for columns)
* np.append(arr, [values]) --> appends values to arr 
* arr.concatenate((arr1, arr2), axis) --> concatenates arr2 to arr along the specified axis (0 for rows and 1 for columns)

'''

'\nAppend and Concatenate\n* np.append(arr1, arr2, axis) --> appends arr2 to arr1 along the specified axis (0 for rows and 1 for columns)\n* np.append(arr, [values]) --> appends values to arr \n* arr.concatenate((arr1, arr2), axis) --> concatenates arr2 to arr along the specified axis (0 for rows and 1 for columns)\n\n'

In [14]:
arr_a = np.array([1,2,3,4,5])
arr_b = np.array([6,7,8,9,10])
print("2 arrays append = \n",np.append(arr_a, arr_b, axis=0))
print("append values in array_a =\n",np.append(arr_a, [11,12,13]))
conc_arr = np.concatenate((arr_a, arr_b), axis=0)
print("concatenated array = \n",conc_arr)

2 arrays append = 
 [ 1  2  3  4  5  6  7  8  9 10]
append values in array_a =
 [ 1  2  3  4  5 11 12 13]
concatenated array = 
 [ 1  2  3  4  5  6  7  8  9 10]


In [15]:
'''
Removal of the values from the array
* np.delete(arr, index, axis) --> deletes the value at the required index along the specified axis (0 for rows and 1 for columns)


'''

'\nRemoval of the values from the array\n* np.delete(arr, index, axis) --> deletes the value at the required index along the specified axis (0 for rows and 1 for columns)\n\n\n'

In [16]:
d_array = np.array([1,2,3,4,5,6,7,8,9])
print("1d array after deletion =",np.delete(d_array, 4, axis=0))
d_2darray = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2d array after deletion, axis 0 = \n",np.delete(d_2darray, 1, axis=0))
print("2d array after deletion, axis 1 = \n",np.delete(d_2darray, 1, axis=1))

1d array after deletion = [1 2 3 4 6 7 8 9]
2d array after deletion, axis 0 = 
 [[1 2 3]
 [7 8 9]]
2d array after deletion, axis 1 = 
 [[1 3]
 [4 6]
 [7 9]]


In [17]:
'''
Stacking
* np.stack((arr1, arr2), axis) --> stacks arr2 on arr1 along the specified axis (0 for rows and 1 for columns)
* np.hstack((arr1, arr2)) --> stacks arr2 on arr1 horizontally
* np.vstack((arr1, arr2)) --> stacks arr2 on arr1 vertically

'''

'\nStacking\n* np.stack((arr1, arr2), axis) --> stacks arr2 on arr1 along the specified axis (0 for rows and 1 for columns)\n* np.hstack((arr1, arr2)) --> stacks arr2 on arr1 horizontally\n* np.vstack((arr1, arr2)) --> stacks arr2 on arr1 vertically\n\n'

In [18]:
S1_array = np.array([1,2,3,4,5])
S2_array = np.array([6,7,8,9,10])
print("stacked array, axis 0 = \n",np.stack((S1_array, S2_array), axis=0))
print("stacked array, axis 1 = \n",np.stack((S1_array, S2_array), axis=1))
print("horizontally stacked array = \n",np.hstack((S1_array, S2_array)))
print("vertically stacked array = \n",np.vstack((S1_array, S2_array)))

stacked array, axis 0 = 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
stacked array, axis 1 = 
 [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
horizontally stacked array = 
 [ 1  2  3  4  5  6  7  8  9 10]
vertically stacked array = 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [19]:
'''
Broadcasting
* Broadcasting is a technique used to perform operations on arrays of different shapes

'''

'\nBroadcasting\n* Broadcasting is a technique used to perform operations on arrays of different shapes\n\n'

In [20]:
broad_array1 = np.array([100,200,300])
discount = 10 #in percentage
discounted_price = broad_array1 - (broad_array1 * discount / 100)
print("discounted_price =",discounted_price)

discounted_price = [ 90. 180. 270.]


In [22]:
'''
Builtin Functions
* np.isnan(arr) --> checks for NaN values in the array #nan means not a number or empty value
* np.nan_to_num(arr, nan = value to be added) --> converts NaN values to the required value, default is 0
 it is also used to convert infinite values to large finite numbers
* np.isinf(arr) --> checks for infinite values in the array

'''

'\nBuiltin Functions\n* np.isnan(arr) --> checks for NaN values in the array #nan means not a number or empty value\n\n'

In [30]:
nan_array = np.array([1, 2, np.nan, 4, 5, np.nan])
print("NaN values in the array =", np.isnan(nan_array))
print("After the nan is replaced, \n",np.nan_to_num(nan_array, nan=10))
inf_array = np.array([1, 2, np.inf, 4, 5, -np.inf])
print("Infinite values in the array =", np.isinf(inf_array))
print("After the inf values are replaced, \n",np.nan_to_num(inf_array, posinf=1000, neginf=-1000))

NaN values in the array = [False False  True False False  True]
After the nan is replaced, 
 [ 1.  2. 10.  4.  5. 10.]
Infinite values in the array = [False False  True False False  True]
After the inf values are replaced, 
 [    1.     2.  1000.     4.     5. -1000.]
